### ISSUE TITLE
Questions About Project

### ISSUE THREAD

**Issue by zicklag** [aclysma/rafx#163]
Hey there! I've just started looking into this library as a possible rendering backend for [Bevy Retrograde](https://github.com/katharostech/bevy_retrograde) and was curious whether or not you see any compelling reasons that I shouldn't use it.

First off, I understand that this library is work-in-progress and subject to changes. I'm OK with that. Something I would be concerned about would be the potential for project abandonment, but it seems like you have been working on it rather steadily for a year or so, and if you don't feel like this project is likely to be dropped for any reason, then I'm fine with that.

I've seen `rafx` before, but one of the reasons I'm looking into it now is the advent of the OpenGL ES 2.0 backend. With Bevy Retrograde we would really like to target WebGL 1.0, for compatibility with the awful iOS Safari web browser. Because we are focusing currently on 2D pixel games this does not feel infeasible.

The other reason that I like the idea of using `rafx` is because it has a native Metal backend. Our current renderer only runs on OpenGL/WebGL and with MacOS deprecating OpenGL we're a little wary of requring OpenGL. Having native metal support would be comforting.

It's also nice that if my team wants to get into 3D rendering sometime ( which we do eventually ), we can continue to use the same rendering abstraction and also get more direct access to more modern graphics API features than the [Luminance](https://github.com/phaazon/luminance-rs) API we are currently using.

---

Anyway, just trying to get a feel for the project status. If I end up using Rafx for my project and I find stuff that I need then I'm usually pretty quick to open issues, discuss, and probably contribute. :) If the project is ready to take external contributions that would be a good sign for me. Thanks!

**Comment by aclysma** [comment]
I'm aware of only two GPU api abstraction layers in rust - rafx and wgpu/gfx-hal. This doc has more comparison between them: https://github.com/aclysma/rafx/blob/master/docs/why_rafx.md  You could also consider non-rust solutions like bgfx, theforge, etc. but I'm assuming you want to stay in rust.

You may already be aware, but wgpu is making some changes in licensing and project structure that I think are really good. I haven't updated that comparison page yet (this is recent news). I think if all you want is a graphics abstraction and you're ok with paying for some safety guarantees, it's a really great project and is the lower risk choice of the two simply because more people are contributing to it and using it.

I think rafx-api will be pretty stable outside of the occasional rename, and the code is small enough that you can probably maintain it if you need to should this project be abandoned (I don't expect that, but I'm also not going to put undue pressure on myself by making hard commitments either.. this is a fun/learning project, and I'm full-time employed elsewhere). I have been working on it for almost 2 years and I'm still interested in it, although I'll probably spend more time on asset pipeline/high-level rendering feature stuff than API abstraction in the near-term.

Speaking of which, rafx isn't meant to be an API abstraction crate. It's meant to be a batteries-included rendering framework with defined workflows for getting asset data onto the screen. For example, I've been investigating editing/exporting workflows in blender this month and coming up with a plan for getting a non-trivial scene imported and rendering. I think rafx is reasonably structured so that you can opt-in to whatever abstraction level makes sense for your needs if you're wanting to do your own thing.

Granted, if you're just interested in API abstraction, the improvements I'm expecting will go in during the rest of the year may not actually be useful to you. As far as contributions go, I'm always open to look at a PR. Just keep in mind that rafx is a more opinionated crate than a project like wgpu. There will be some features here/there that could be useful to some people that we will decide not to include due to incomplete/inconsistent support across GPU APIs or the higher-level framework design we have in mind not benefiting from it.

**Comment by zicklag** [comment]
Awesome, thanks for the rundown.

Right now the compelling thing about rafx compared to WGPU is the OpenGL backend, which is very work-in-progress in gfx/wgpu.

Also, looking into the `rafx-framework` design, I'm liking the render "feature" and "phase" concepts. The features concept is something like what I already had to implement myself in my Luminance-based renderer, but I have little experience actually writing renderers so having some structure in place for organizing the rendering "plugins" and phases is useful.

> Speaking of which, rafx isn't meant to be an API abstraction crate. It's meant to be a batteries-included rendering framework with defined workflows for getting asset data onto the screen.

I actually think that's really cool. Like you mention in your comparison doc, I don't think there are a lot of libraries filling this spot. 

Because I'm focused on using Bevy for my games right now, and Bevy hasn't integrated with Distill yet, I'm going to hooking rafx into Bevy's current asset loader, but once Bevy switches, I might be able to use more of rafx than just the API abstraction.

Your ideas about including a full asset workflow actually seems like it's in a similar direction to what I'd want to get going in the future with [Arsenal](https://github.com/katharostech/arsenal).

---

It sounds like our general ideas overlap enough that I'm willing to try it and see what happens. :)
