### ISSUE TITLE
Composite alpha flag and transparent window

### ISSUE THREAD

**Issue by kasper0406** [aclysma/rafx#213]
I was trying to make a transparent window using the Skulpin crate. However, because the Vulkan swapchain is created using the `vk::CompositeAlphaFlagsKHR::OPAQUE` composite alpha setting (https://github.com/aclysma/rafx/blob/v0.0.14/rafx-api/src/backends/vulkan/swapchain.rs#L672) the alpha component is ignore as per https://www.khronos.org/registry/vulkan/specs/1.2-extensions/man/html/VkCompositeAlphaFlagBitsKHR.html. Changing the composite alpha setting to either pre-multiplied or post-multiplied makes the window appear transparent as expected.

What are your thoughts on changing this setting, or make it user configurable?

**Comment by aclysma** [comment]
One option would be to add a flag to RafxSwapchainDef but we shouldn’t add vulkan-specific stuff to that struct. Also you’re doing something very specific and want full control so I think we should find a solution that lets you pass exactly what you want to vulkan instead of abstracting.

We could add something to RafxSwapchainVk::new() (although it would make it inconstant with other swapchain objects, so not ideal but better than nothing.)

Finally you could fork rafx-api, cargo patch it in, and hack it to do whatever you want. Obvious downsides there, but it gets you something that works immediately. It may be worth doing temporarily to give us some time to decide on a long term solution.

I guess another option would be to make the swapchain yourself directly with the vulkan API. The design of rafx is meant to expose internals to you and let you call straight into APIs, not hide them from you. Maybe there could be a way to construct that swapchain wrapper with a user-made swapchain, or have a trait object you implement that rafx can call into when a swapchain rebuild is needed.

BTW skulpin is not something I plan to do improvements on going forward, and if it ever seriously breaks I will probably just drop it. So please be prepared for that if you plan to use it for anything more than prototyping/toy usage :)

**Comment by kasper0406** [comment]
Thanks for your response. For now I did the cargo patch approach, and that works fine. I'll try to look into if I can somehow get the swapchain exposed through Skulpin, maybe then I can simple change the composite alpha setting as you suggest.

Thanks for the heads up about Skulpin. For now it's just toy usage, so should be alright for now.
Since I have a workaround I'll go ahead and close this now.
