### ISSUE TITLE
add note about build deps in readme

### ISSUE THREAD

**Issue by adsick** [aclysma/rafx#98]
imagine not everyone have cmake installed

**Comment by adsick** [comment]
actually messed up more than 1 hour trying to compile it and still did not succeeded....
I have installed cmake and it says it is not installed, I restarted my laptop and it still says it is not installed...
are guys sure it is a good idea to have C++ dependencies? i recommend using winit and egui

**Comment by adsick** [comment]
btw I am on Windows if it matters

**Comment by aclysma** [comment]
Do you know what is trying to build that's using cmake? I'm thinking it might be shaderc or imgui but I'm not sure, so I'd appreciate the info. I think cmake is installed for other reasons on all the machines I use, so I didn't notice it. I also don't recall adding it to CI as a dependency, although it's possible it's available by default in github's CI environment.

I don't think avoiding C++ dependencies will be possible. I'd rather not re-implement a GLSL compiler or maintain a spirv_cross equivalent. That said, some crates (like SDL2 unfortunately) are flaky to build. I'd rather see those issues be fixed than throw out an option that has shipped a huge number of titles on many platforms. (I've thought about making a minimal SDL2 crate, I only use a very small fraction of APIs from SDL2).

Regarding winit and egui, rafx uses raw-window-handle so you can use whatever windowing crate you would like. I use SDL2 because of bugs like this https://github.com/rust-windowing/winit/issues/1418 that have been open for a year and would block shipping a real product. I will probably switch to egui at some point for the demo. It was not as mature a year ago when I went with imgui. But there's no reason why egui could not be implemented in your own project that uses rafx.

**Comment by aclysma** [comment]
Removed cmake from path on a windows machine, it's used by SDL2 and some upstream crates in the shader pipeline. (So switching away from SDL2 would not remove the need to have cmake installed)

Added a note in the README: https://github.com/aclysma/rafx/commit/0047f2ce734353e48af654acafc93ebad64b2daa

Happy to look at an error/compile message if you have one

**Comment by adsick** [comment]
> Do you know what is trying to build that's using cmake? I'm thinking it might be shaderc or imgui but I'm not sure, so I'd appreciate the info. I think cmake is installed for other reasons on all the machines I use, so I didn't notice it. 
==It fails when compiling sdl2.==
> I don't think avoiding C++ dependencies will be possible. I'd rather not re-implement a GLSL compiler or maintain a spirv_cross equivalent. That said, some crates (like SDL2 unfortunately) are flaky to build. 
==I'm not sure, but projects like wgpu and gfx now are working hard to get rid of C++ deps, so consider what they've done in order to do so==

**Comment by aclysma** [comment]
The C/C++ dependencies that I use are mature, stable, and successfully used in commercially shipped titles. For me that carries a lot of weight.

If you are still unable to build after installing cmake, please feel free to reopen/paste the compile error. I do frequently build/run rafx on windows.
